version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /code/node_modules
      - /code/static/builds-development
      - /code/static/webpack
    ports:
      - "8000:8000"
    depends_on:
      - db